### ISSUE TITLE
Some functions called in protocol.py are not defined

### ISSUE THREAD

**Issue by frdwrd** [zcash-hackworks/zbxcat#28]
https://github.com/zcash-hackworks/zbxcat/blob/8a070461cda2da0a759686b80a0667486f97e8cd/xcat/protocol.py#L170
https://github.com/zcash-hackworks/zbxcat/blob/8a070461cda2da0a759686b80a0667486f97e8cd/xcat/protocol.py#L175

Is it possible these got renamed? Or were never planned but never implemented?

These were difficult to track down with the wildcard imports. Have we considered refactoring those out?

**Comment by frdwrd** [comment]
Similar here:

https://github.com/zcash-hackworks/zbxcat/blob/master/xcat/bitcoinRPC.py#L50-L58
https://github.com/zcash-hackworks/zbxcat/blob/master/xcat/bitcoinRPC.py#L130

**Comment by arcalinea** [comment]
Thanks for pointing out, yes, wildcat imports definitely need refactoring. And I thought I'd removed that call to zcashd in the bitcoinRPC file, will fix.

**Comment by arcalinea** [comment]
Refactored a bit and removed some dead code in protocol.py. Also removed that call to zcashd. There's definitely more to do, but I'll go ahead and close this issue since I broke out the remaining concerns into separate issues. Thanks for the feedback!
